version: '3.1'
services:
  apt-cacher:
    build:
      context: ./containers/scivey/apt-cacher-ng
    image: scivey/apt-cacher-ng:latest
    ports:
    - "3142:3142"
    volumes:
    - ./.db-data/apt-cacher:/var/cache/apt-cacher-ng
  pypi-server:
    image: codekoala/pypi:latest
    ports:
    - "9053:80"
    volumes:
    - ./.db-data/pypi-server:/srv/pypi
    environment:
      - PYPI_ROOT=/srv/pypi/data

