#!/bin/bash
. $(dirname ${BASH_SOURCE[0]})/common.sh

function runit() {
    pushd ${PYPICLOUD_DIR}
    local just
    PS1=${PS1:-""}
    if [[ ! -d .env ]]; then
        virtualenv -p python2.7 .env
    fi
    . .env/bin/activate
    if [[ ! -e .env/bin/pserve ]]; then
        pip install -r requirements.txt
    fi
    exec pserve -v conf/server.ini
}

runit
